START TRANSACTION ;
INSERT INTO `contacts`.`relationship` (`name`) VALUES ('Свободен');
INSERT INTO `contacts`.`relationship` (`name`) VALUES ('В отношениях');
INSERT INTO `contacts`.`relationship` (`name`) VALUES ('Помолвлен');
INSERT INTO `contacts`.`relationship` (`name`) VALUES ('В браке');
INSERT INTO `contacts`.`relationship` (`name`) VALUES ('Все сложно');
INSERT INTO `contacts`.`relationship` (`name`) VALUES ('В активном поиске');
INSERT INTO `contacts`.`relationship` (`name`) VALUES ('Влюблён');
COMMIT;

START TRANSACTION ;
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(30, 'Афганистан', 93);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(21, 'Албания', 355);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(22, 'Алжир', 213);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(23, 'Американское Самоа', 1684);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(26, 'Андорра', 376);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(25, 'Ангола', 244);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(24, 'Ангилья', 1264);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(27, 'Антигуа и Барбуда', 1268);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(28, 'Аргентина', 54);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(6, 'Армения', 374);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(29, 'Аруба', 297);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(19, 'Австралия', 61);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(20, 'Австрия', 43);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(5, 'Азербайджан', 994);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(31, 'Багамы', 1242);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(34, 'Бахрейн', 973);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(32, 'Бангладеш', 880);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(33, 'Барбадос', 1246);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(3, 'Беларусь', 375);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(36, 'Бельгия', 32);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(35, 'Белиз', 501);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(37, 'Бенин', 229);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(38, 'Бермуды', 1441);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(47, 'Бутан', 975);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(235, 'Бонайре, Синт-Эстатиус и Саба', 5997);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(41, 'Босния и Герцеговина', 387);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(42, 'Ботсвана', 267);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(43, 'Бразилия', 55);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(44, 'Бруней-Даруссалам', 673);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(39, 'Болгария', 359);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(45, 'Буркина-Фасо', 226);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(46, 'Бурунди', 257);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(91, 'Камбоджа', 855);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(92, 'Камерун', 237);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(10, 'Канада', 1);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(149, 'Острова Кайман', 1345);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(213, 'Центрально-Африканская Республика', 236);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(214, 'Чад', 235);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(216, 'Чили', 56);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(97, 'Китай', 86);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(98, 'Колумбия', 57);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(99, 'Коморы', 269);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(100, 'Конго', 242);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(150, 'Острова Кука', 682);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(102, 'Коста-Рика', 506);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(212, 'Хорватия', 385);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(104, 'Куба', 53);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(138, 'Кюрасао', 599);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(95, 'Кипр', 357);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(215, 'Чехия', 420);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(73, 'Дания', 45);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(231, 'Джибути', 253);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(74, 'Доминика', 1767);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(75, 'Доминиканская Республика', 1809);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(221, 'Эквадор', 593);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(76, 'Египет', 20);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(166, 'Сальвадор', 503);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(222, 'Экваториальная Гвинея', 240);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(223, 'Эритрея', 291);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(14, 'Эстония', 372);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(224, 'Эфиопия', 251);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(204, 'Фарерские острова', 298);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(205, 'Фиджи', 679);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(207, 'Финляндия', 358);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(209, 'Франция', 33);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(210, 'Французская Гвиана', 594);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(211, 'Французская Полинезия', 689);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(56, 'Габон', 241);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(59, 'Гамбия', 220);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(7, 'Грузия', 995);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(65, 'Германия', 49);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(60, 'Гана', 233);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(66, 'Гибралтар', 350);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(71, 'Греция', 30);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(70, 'Гренландия', 299);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(69, 'Гренада', 1473);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(61, 'Гваделупа', 590);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(72, 'Гуам', 1671);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(62, 'Гватемала', 502);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(236, 'Гернси', 44);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(63, 'Гвинея', 224);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(64, 'Гвинея-Бисау', 245);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(58, 'Гайана', 592);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(57, 'Гаити', 509);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(67, 'Гондурас', 504);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(68, 'Гонконг', 852);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(50, 'Венгрия', 36);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(86, 'Исландия', 354);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(80, 'Индия', 91);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(81, 'Индонезия', 62);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(83, 'Ирак', 964);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(85, 'Ирландия', 353);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(147, 'Остров Мэн', 44);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(8, 'Израиль', 972);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(88, 'Италия', 39);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(228, 'Ямайка', 1876);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(229, 'Япония', 81);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(237, 'Джерси', 44);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(82, 'Иордания', 962);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(4, 'Казахстан',77);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(94, 'Кения', 254);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(96, 'Кирибати', 686);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(105, 'Кувейт', 965);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(11, 'Кыргызстан', 996);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(12, 'Латвия', 371);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(109, 'Ливан', 961);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(107, 'Лесото', 266);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(108, 'Либерия', 231);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(110, 'Ливия', 218);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(111, 'Лихтенштейн', 423);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(13, 'Литва', 370);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(112, 'Люксембург', 352);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(115, 'Мадагаскар', 261);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(118, 'Малави', 265);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(119, 'Малайзия', 60);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(121, 'Мальдивы', 960);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(120, 'Мали', 223);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(122, 'Мальта', 356);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(125, 'Маршалловы Острова', 692);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(124, 'Мартиника', 596);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(114, 'Мавритания', 222);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(113, 'Маврикий', 230);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(126, 'Мексика', 52);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(129, 'Монако', 377);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(130, 'Монголия', 976);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(230, 'Черногория', 382);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(131, 'Монтсеррат', 1664);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(123, 'Марокко', 212);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(128, 'Мозамбик', 258);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(132, 'Мьянма', 95);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(133, 'Намибия', 264);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(134, 'Науру', 674);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(135, 'Непал', 977);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(139, 'Нидерланды', 31);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(143, 'Новая Каледония', 687);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(142, 'Новая Зеландия', 64);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(140, 'Никарагуа', 505);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(136, 'Нигер', 227);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(137, 'Нигерия', 234);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(141, 'Ниуэ', 683);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(148, 'Остров Норфолк', 672);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(174, 'Северные Марианские острова', 1670);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(144, 'Норвегия', 47);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(146, 'Оман', 968);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(152, 'Пакистан', 92);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(153, 'Палау', 680);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(155, 'Панама', 507);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(156, 'Папуа — Новая Гвинея', 675);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(157, 'Парагвай', 595);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(158, 'Перу', 51);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(206, 'Филиппины', 63);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(160, 'Польша', 48);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(161, 'Португалия', 351);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(162, 'Пуэрто-Рико',1939);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(93, 'Катар', 974);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(163, 'Реюньон', 262);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(165, 'Румыния', 40);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(164, 'Руанда', 250);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(178, 'Сент-Китс и Невис', 1869);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(179, 'Сент-Люсия', 1758);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(180, 'Сент-Пьер и Микелон', 508);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(177, 'Сент-Винсент', 1784);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(167, 'Самоа', 685);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(168, 'Сан-Марино', 378);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(170, 'Саудовская Аравия', 966);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(176, 'Сенегал', 221);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(181, 'Сербия', 381);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(175, 'Сейшелы', 248);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(190, 'Сьерра-Леоне', 232);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(182, 'Сингапур', 65);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(184, 'Словакия', 421);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(185, 'Словения', 386);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(186, 'Соломоновы Острова', 677);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(187, 'Сомали', 252);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(227, 'Южно-Африканская Республика', 27);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(232, 'Южный Судан', 211);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(87, 'Испания', 34);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(220, 'Шри-Ланка', 94);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(188, 'Судан', 249);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(189, 'Суринам', 597);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(219, 'Шпицберген и Ян Майен', 4779);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(171, 'Свазиленд', 268);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(218, 'Швеция', 46);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(217, 'Швейцария', 41);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(16, 'Таджикистан', 992);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(191, 'Таиланд', 66);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(194, 'Того', 228);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(195, 'Токелау', 690);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(196, 'Тонга', 676);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(197, 'Тринидад и Тобаго', 1868);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(199, 'Тунис', 216);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(200, 'Турция', 90);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(17, 'Туркменистан', 993);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(151, 'Острова Теркс и Кайкос', 1649);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(198, 'Тувалу', 688);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(201, 'Уганда', 256);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(2, 'Украина', 380);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(145, 'Объединенные Арабские Эмираты', 971);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(203, 'Уругвай', 598);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(18, 'Узбекистан', 998);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(48, 'Вануату', 678);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(202, 'Уоллис и Футуна', 681);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(78, 'Западная Сахара', 212);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(89, 'Йемен', 967);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(77, 'Замбия', 260);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(79, 'Зимбабве', 263);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(40, 'Боливия',591);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(233, 'Ватикан',39);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(49, 'Великобритания',44);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(51, 'Венесуэла',58);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(52, 'Виргинские острова, Британские',1284 );
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(53, 'Виргинские острова, США',1340);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(54, 'Восточный Тимор',62);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(55, 'Вьетнам',84);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(84, 'Иран',98);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(90, 'Кабо-Верде',238);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(101, 'Конго, демократическая республика',243);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(103, 'Кот д`Ивуар',225);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(106, 'Лаос',856);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(116, 'Макао',853);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(117, 'Македония',389);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(127, 'Микронезия, федеративные штаты',691);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(15, 'Молдова',373);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(159, 'Питкерн',64);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(1, 'Россия',7);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(9, 'США',1);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(169, 'Сан-Томе и Принсипи',239);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(172, 'Святая Елена',247);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(173, 'Северная Корея',850);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(183, 'Сирийская Арабская Республика',963);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(192, 'Тайвань',886);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(193, 'Танзания',255);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(208, 'Фолклендские острова',500);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(226, 'Южная Корея',82);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(234, 'Синт-Мартен',1721);
INSERT INTO `contacts`.`country` (`id`, `name`, `phone_code`) VALUES(154, 'Палестина',970);
commit;